name: CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Copy project files using rsync
      run: |
        sshpass -p "${{ secrets.PASSWORD }}" rsync -avz --delete \
          -e "ssh -p 2222 -o StrictHostKeyChecking=no" ./ ${{ secrets.USER }}@${{ secrets.HOST }}:/home/${{ secrets.USER }}/app

    - name: Deploy to VM via SSH with password
      run: |
        sshpass -p "${{ secrets.PASSWORD }}" ssh -p 2222 -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} << 'EOF'
          cd ~/app
          docker compose down || true
          docker compose build
          docker compose up -d
        EOF
