name: CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code on self-hosted runner
      uses: actions/checkout@v3

    - name: Deploy to remote VM via SSH
      env:
        GIT_REPO: "git@github.com:yourusername/yourrepo.git"  # Change to your repo SSH URL
        APP_DIR: "/home/${{ secrets.USER }}/app"
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} << EOF
          if [ ! -d "$APP_DIR" ]; then
            echo "Project directory does not exist, cloning repo..."
            git clone $GIT_REPO $APP_DIR
          else
            echo "Project directory exists, pulling latest changes..."
            cd $APP_DIR
            git pull origin main
          fi
          cd $APP_DIR
          docker compose down || true
          docker compose build
          docker compose up -d
        EOF

