name: CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to VM via SSH with password
      run: |
        sshpass -p "${{ secrets.PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} << 'EOF'
          if [ ! -d ~/app ]; then
            git clone https://github.com/M2iYahya/gestion-des-salles-de-tp ~/app
          else
            cd ~/app
            git pull
          fi
          cd ~/app
          docker compose down || true
          docker compose build
          docker compose up -d
        EOF
